"""create registry tables

Revision ID: 0001
Revises:
Create Date: 2026-09-16

Written by hand rather than autogenerated so it can be reviewed without a
live database. ``alembic check`` will confirm it matches the models.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "containers",
        # The ISO 6346 number is the natural key.
        sa.Column("number", sa.String(length=11), nullable=False),
        sa.Column("owner_code", sa.String(length=3), nullable=False),
        sa.Column("equipment_category", sa.String(length=1), nullable=False),
        sa.Column("serial_number", sa.String(length=6), nullable=False),
        sa.Column("check_digit", sa.SmallInteger(), nullable=False),
        sa.Column("size_type_code", sa.String(length=4), nullable=False),
        sa.Column("cleanliness", sa.String(length=16), nullable=False),
        sa.Column("structural", sa.String(length=16), nullable=False),
        sa.Column("cargo_grade", sa.String(length=32), nullable=False),
        sa.Column("identified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("identified_by", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("number"),
    )
    op.create_index("ix_containers_owner_code", "containers", ["owner_code"])
    op.create_index("ix_containers_serial_number", "containers", ["serial_number"])
    op.create_index("ix_containers_size_type_code", "containers", ["size_type_code"])
    op.create_index("ix_containers_cargo_grade", "containers", ["cargo_grade"])
    op.create_index("ix_containers_identified_at", "containers", ["identified_at"])

    op.create_table(
        "inspections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("container_number", sa.String(length=11), nullable=False),
        sa.Column("cleanliness", sa.String(length=16), nullable=False),
        sa.Column("structural", sa.String(length=16), nullable=False),
        sa.Column("cargo_grade", sa.String(length=32), nullable=False),
        sa.Column("inspected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inspected_by", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("evidence_image_ref", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["container_number"], ["containers.number"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inspections_container_number", "inspections", ["container_number"]
    )
    op.create_index("ix_inspections_inspected_at", "inspections", ["inspected_at"])


def downgrade() -> None:
    op.drop_index("ix_inspections_inspected_at", table_name="inspections")
    op.drop_index("ix_inspections_container_number", table_name="inspections")
    op.drop_table("inspections")

    op.drop_index("ix_containers_identified_at", table_name="containers")
    op.drop_index("ix_containers_cargo_grade", table_name="containers")
    op.drop_index("ix_containers_size_type_code", table_name="containers")
    op.drop_index("ix_containers_serial_number", table_name="containers")
    op.drop_index("ix_containers_owner_code", table_name="containers")
    op.drop_table("containers")
